@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "preview:CommandResult" as PreviewResult LOGIC_COLOR
participant "a:Supplier<CommandResult>" as ConfirmationAction LOGIC_COLOR
participant "final:CommandResult" as FinalResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

' --- First call: preview only ---
[-> LogicManager : execute(":delete 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(":delete 1")
activate AddressBookParser

create DeleteCommandParser
AddressBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> AddressBookParser
deactivate DeleteCommandParser

AddressBookParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser :
deactivate DeleteCommand

DeleteCommandParser --> AddressBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> AddressBookParser
destroy DeleteCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteCommand : execute(m)
activate DeleteCommand

DeleteCommand -> Model : getFilteredPersonList()
activate Model
Model --> DeleteCommand
deactivate Model

create PreviewResult
DeleteCommand -> PreviewResult : <<create>>\n(feedback + confirmationAction)
activate PreviewResult

PreviewResult --> DeleteCommand
deactivate PreviewResult

DeleteCommand --> LogicManager : preview result
deactivate DeleteCommand

LogicManager -> PreviewResult : isAwaitingConfirmation()
LogicManager -> PreviewResult : getConfirmationAction()
PreviewResult --> LogicManager : a
LogicManager -> LogicManager : pendingConfirmation = a


[<-- LogicManager : preview shown
deactivate LogicManager
' --- Second call: confirmation ---
[-> LogicManager : execute("yes")
activate LogicManager

note right of LogicManager
pendingConfirmation != null, so parsing is skipped
end note

LogicManager -> ConfirmationAction : get()
activate ConfirmationAction

ConfirmationAction -> Model : deletePerson(personToDelete)
activate Model
Model --> ConfirmationAction
deactivate Model

ConfirmationAction -> Model : deleteTags(personToDelete)
activate Model
Model --> ConfirmationAction
deactivate Model

create FinalResult
ConfirmationAction -> FinalResult : <<create>>\n("Deleted Person ...")
activate FinalResult
FinalResult --> ConfirmationAction
deactivate FinalResult

ConfirmationAction --> LogicManager : final result
deactivate ConfirmationAction

[<-- LogicManager : deletion confirmed
deactivate LogicManager
@enduml
