@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command ":delete 5"

class MM as "<u>:ModelManager</u>"
class Undo as "<u>:Runnable</u>"

MM -right-> Undo : undoAction

note bottom of Undo : Re-adds the deleted\nperson and their tags
@enduml
