@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command ":add n/David"

class MM as "<u>:ModelManager</u>"
class Undo as "<u>:Runnable</u>"

MM -right-> Undo : undoAction

note bottom of Undo : Deletes David and his tags\n(previous undo action overwritten)
@enduml
