@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command ":undo"

class MM as "<u>:ModelManager</u>"

note bottom of MM : undoAction = null\n(action was executed then cleared)
@enduml
